name: drawing_on_demand_web_admin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  nb_utils: ^6.0.4
  flutter_svg: ^1.1.1+1
  provider: ^6.1.1
  charts_flutter: ^0.12.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_guid: ^0.3.1
  intl: ^0.17.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.2
  http: ^1.1.0
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  url_strategy: ^0.2.0
  validators: ^3.0.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  email_otp: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: ubuntu-bold
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
  
